name: Package and release

on:
  push:
    tags:
      - '**'

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}

    steps:
      - name: Clone project
        uses: actions/checkout@v1

      - name: Package and release
        uses: BigWigsMods/packager@v1

      # another example where we supply additional arguments, this example is specifically to release
      # for the Classic version of the game
      - name: Package and release for Classic
        uses: BigWigsMods/packager@v1
        with:
          args: -g bcc -a 9rN4Qz6D
